### PR TITLE
Battlepass

### PR DESCRIPTION
**Pull request by VladimirtheGreatest**
Added media queries, please have a look at that and let me know if there are any errors or things to improve.

### CODE REVIEW

**Review by sasigit7 — COMMENTED** [review]
Remove Duplicate code from Line 223 to 227:

<script src="js/javascript.js"></script>
</body>
</html>

**Review by ahmedserifoski — COMMENTED** [review]
The Image is too zoomed in, u can't see the characters
when the window width drops under 769 the image is shrunk instead of just showing the left action-guy-character

**Comment by VladimirtheGreatest** [comment]
> The Image is too zoomed in, u can't see the characters
> when the window width drops under 769 the image is shrunk instead of just showing the left action-guy-character

I use two different images, one is for the desktop version (which is identical to the original, the second one is the mobile version( that is the "zoomed in" one) I don`t personally like that left guy appearing on the mobile screen so I pushed him out with the padding.

**Comment by VladimirtheGreatest** [comment]
> Remove Duplicate code from Line 223 to 227:
> 
> <script src="js/javascript.js"></script>

Fixed, thanks!

**Review by stephairth — CHANGES_REQUESTED** [review]
Overall looks good, but I have a few nitpicks!

The position of the character is a bit awkward on my screen):
(my laptop's display is 13.3-inch / 2560 x 1600, a pretty standard size for personal laptops)
awkward position on steph's screen

for regular ipads, the dude on the side seems a bit vertically stretched: 
stretchy dude on ipad

for ipad pro, the positioning for the dude on the side is the same as on my computer (a bit awkward/we can only half see him) and there is a thin white line on the right side:
awkward position on ipad pro

**Comment by VladimirtheGreatest** [comment]
I will definitely add more media queries. Thanks

**Comment by VladimirtheGreatest** [comment]
> Overall looks good, but I have a few nitpicks!
> 
> The position of the character is a bit awkward on my screen):
> (my laptop's display is 13.3-inch / 2560 x 1600, a pretty standard size for personal laptops)

Please have a look at that again and tell me if it looks good. I completely changed the mobile background and fixed that issue that was possibly causing that awkward position, however keep in mind that even the original website cuts that part of the image on tablets as well.

**Review by stephairth — COMMENTED** [review]
It still looks the same to me on my laptop and on the dev tools for ipad/pro, but after seeing the original ipad version I think yours is still better

**Comment by VladimirtheGreatest** [comment]
Added more media queries, pirate dude should be now visible at all times even on small laptops, big laptops and tablets as well. This branch has got some conflicts since I have not downloaded recent development branch with media queries and hover effects from Steph etc so after your review (if you are satisfied) I will reopen this pull request.

**Review by stephairth — COMMENTED** [review]
Looking good! The guy is still a bit vertically stretched when I view the page on my laptop:
vlad's version on steph's laptop

Compared with the original:
original version on steph's laptop

He's also a bit stretched on the ipadpro version: 
vlad's version on ipadpro

But I think your ipadpro version currently looks better than the original's, where you can't see him at all: 
original on ipad pro

The phone version looks perfect imo 🙆‍♀️I think once you get the side dude un-stretched the laptop and ipadpro versions will also be good to go.

**Review by stephairth — APPROVED** [review]
Yay, success! Looks good on all screens for me now 🙆‍♀️

**Review by ahmedserifoski — COMMENTED** [review]
I see my MS1 mixed up with the battlepass section
If I ignore that it's great :P

**Comment by VladimirtheGreatest** [comment]
> I see my MS1 mixed up with the battlepass section
> If I ignore that it's great :P

Fixed.

**Review by stephairth — APPROVED** [review]
Looks good to me 🦜

**Review by sasigit7 — APPROVED** [review]
Looks good to me.

**Pull request merged**
