### PR TITLE
add @media queries

### PR DESCRIPTION
**Pull request by ahmedserifoski**
check out the media queries

### CODE REVIEW

**Review by stephairth — COMMENTED** [review]
The responsivity looks good for big screens and iPad (although I can see the tiniest white line on the right side), but when I open it for the various mobile settings (iPhone SE etc) the image/content doesn't stretch to fit the screen size. Maybe a problem with media queries OR with the image (I know you said you were going to try to get a higher quality image, maybe that will fix it)??

On line 113/114 of your CSS you have two "font-size:" specifications--not sure which one you want, but the W3C CSS Validator threw an error for that. 

Otherwise looks good! 🙆‍♀️

**Review by stephairth — COMMENTED** [review]
Looks good to me! I would remove "user-scalable=no", as this is an anti-pattern for accessibility--some people need to be able to scale the page to zoom in on things they couldn't otherwise read or see clearly. otherwise looks good to go! 🙆‍♀️

**Review by VladimirtheGreatest — COMMENTED** [review]
There are some conflicts, I think it will be better if you pull the latest development branch, add your recent stuff and re-upload this branch so you do not have to waste your time.

**Review by stephairth — APPROVED** [review]
Looks good to me! 🙆‍♀️

**Review by VladimirtheGreatest — CHANGES_REQUESTED** [review]
Just a small detail, I think you need to add extra media query. Check the break-point width in between 1401 and 1491. Your background image is not covering the whole screen, there is a small white gap. Try to change the media query on line 222 instead of min-width 1492px, try 1401 (or add another media query min-width 1401px max-width 1491px, background-size: 100vw or 100% or just change the global css for this section). Good job with the use of flexbox and margins, it looks very smooth.

**Review by sasigit7 — APPROVED** [review]
Looks good.

**Pull request closed without merging**
