### PR TITLE
Feature/nav/search user about

### PR DESCRIPTION
**Pull request by stephairth**
Just updated some styling for the sign-in and developers pages! Pull request to masterpiece 3 as requested during today's meeting ✌️🐻Have a good one

### CODE REVIEW

**Comment by VladimirtheGreatest** [comment]
This is how it looks like on my PC. 
navbar
By the way, I would personally get rid of that search bar, we already have a search icon and since there is no back-end, you can save some time and focus on something else. It would help me as well.

**Review by ahmedserifoski — APPROVED** [review]
yeah sure, I agree

**Comment by stephairth** [comment]
Does the new version I pushed today work better? I added an event listener for window size so the problem with the nav links reappearing should be gone now. I'd rather keep it in if it's working

**Review by sasigit7 — APPROVED** [review]
looks good now

**Pull request closed without merging**
