### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by VladimirtheGreatest**
I deleted your paragraphs because I dont like them. This is my solution.

### CODE REVIEW

**Review by stephairth — APPROVED** [review]
Yeah we didn't need those paragraphs

**Review by sasigit7 — APPROVED** [review]
I reviewed and approved your request

**Review by ahmedserifoski — CHANGES_REQUESTED** [review]
no I don't like it

**Review by ahmedserifoski — CHANGES_REQUESTED** [review]
leave them !

**Pull request merged**
