### PR TITLE
Added Files Via Upload

### PR DESCRIPTION
**Pull request by sasigit7**
Fixed Following bugs: 
1. Removed slick ReadMe file
2. Added previous and next icons for Image carousel in the mobile version
3. Moved JQuery Code from HTML to javascript.js
4. Written media query for the desktop version, so that MainSection 2 goes into mainSection1.

Let me know if any further changes need to be done.

### CODE REVIEW

**Review by ahmedserifoski — APPROVED** [review]
look good

**Review by VladimirtheGreatest — APPROVED** [review]
Looks great. Why are you merging with the development and not the previous masterpiece4?

**Comment by sasigit7** [comment]
> Looks great. Why are you merging with the development and not the previous masterpiece4?

Changed base to masterpiece4.

**Comment by stephairth** [comment]
Why does masterpiece 5 not have the popup pages or the expanding search bar? :0

**Comment by VladimirtheGreatest** [comment]
> Why does masterpiece 5 not have the popup pages or the expanding search bar? :0

It is in masterpiece6.

**Review by stephairth — APPROVED** [review]

**Pull request merged**
