### PR TITLE
Feature/nav/search user about

### PR DESCRIPTION
**Pull request by stephairth**
Okay! Here I've added: 
1) the search form and the js for its dis/appearing (needs an event listener for when the window size is changed and maybe something to make the transition smoother, otherwise fine I think)
2) the sign-in popup (needs springy css animations)
3) the about us page (needs to be prettier / please everyone add your info etc)

Lemme know what you think!

### CODE REVIEW

**Review by VladimirtheGreatest — COMMENTED** [review]
Looks great, especially that developers section, there are probably few conflicts since the navbar looks weird on the small screen.

**Comment by stephairth** [comment]
@VladimirtheGreatest Weird, I just checked it on all the screen sizes in dev tools and didn't see any problems. Let's check it today in our meeting!

**Comment by VladimirtheGreatest** [comment]
> @VladimirtheGreatest Weird, I just checked it on all the screen sizes in dev tools and didn't see any problems. Let's check it today in our meeting!

Sorry that was a wrong branch, it looks ok. There is only one weird media query 
image

**Review by sasigit7 — CHANGES_REQUESTED** [review]
Use **target=_blank** attribute value on "a" tags, So that linked pages, will open in a separate window or tab.

**Comment by stephairth** [comment]
@sasigit7 good shout! just added that to all of them

**Comment by VladimirtheGreatest** [comment]
My discord is not working guys, do you have the same issue?

**Pull request closed without merging**
